---
- name: Copy the sample database configuration file.
  copy:
    src: '/usr/share/openldap-servers/DB_CONFIG.example'
    dest: '/var/lib/ldap/DB_CONFIG'
    remote_src: 'yes'
    owner: 'ldap'
    group: 'ldap'
  register: slapd_db_config

- name: Reload the OpenLDAP service.
  shell: echo ''
  notify: 'Ensure OpenLDAP service is enabled'
  when: slapd_yum_status is changed or slapd_db_config is changed

- name: Force the handler to run immediately.
  meta: flush_handlers

- name: Certificates LDAP Data Interchange Files transfer.
  template:
    src: 'certs.ldif.j2'
    dest: '/tmp/certs.ldif'
    owner: 'ldap'
    group: 'ldap'
    mode: '0644'
  when: slapd_ssl | bool

- name: Enable the OpenLDAP TLS Configuration.
  command: 'ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/certs.ldif'
  when: slapd_ssl | bool
  register: slapd_conf_status
  failed_when:
    - "'already exists' not in slapd_conf_status.stdout"
    - "'modifying entry' not in slapd_conf_status.stdout"
    - "'adding new entry' not in slapd_conf_status.stdout"

- name: Root password LDAP Data Interchange Files transfer.
  template:
    src: 'olcdatabase.ldif.j2'
    dest: '/tmp/olcdatabase.ldif'
    owner: 'ldap'
    group: 'ldap'
    mode: '0644'

- name: Modify root password for OpenLDAP.
  command: 'ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/olcdatabase.ldif'
  failed_when:
    - "'already exists' not in slapd_conf_status.stdout"
    - "'modifying entry' not in slapd_conf_status.stdout"
    - "'adding new entry' not in slapd_conf_status.stdout"

- name: OpenLDAP configuration file transfer.
  template:
    src: 'slapd.j2'
    dest: '/etc/sysconfig/slapd'
    owner: 'root'
    group: 'root'
    mode: '644'
  register: slapd_conf_file

- name: Reload the OpenLDAP service.
  shell: echo ''
  notify: 'Ensure OpenLDAP service is enabled'
  when: slapd_conf_file is changed

- name: Force the handler to run immediately.
  meta: flush_handlers
