---
- name: OpenLDAP systemd configuration.
  lineinfile:
    state: 'present'
    dest: '/lib/systemd/system/slapd.service'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    insertafter: '\[Service\]'
  loop:
    - { regexp: '^LimitNOFILE', line: 'LimitNOFILE=10240' }
  register: slapd_systemd

- name: Creating OpenLDAP database and logs storage directory.
  file:
    dest: '{{ slapd_path }}/ldap'
    state: 'directory'
    owner: 'ldap'
    group: 'ldap'
    mode: '0750'

- name: Database configuration transfer.
  template:
    src: 'DB_CONFIG.j2'
    dest: '/var/lib/ldap/DB_CONFIG'
    owner: 'ldap'
    group: 'ldap'
  register: slapd_db_config

- name: OpenLDAP configuration file transfer.
  template:
    src: 'slapd.j2'
    dest: '/etc/sysconfig/slapd'
    owner: 'root'
    group: 'root'
    mode: '644'
  register: slapd_conf_file

- name: LDAP Data Interchange files transfer.
  template:
    src: '{{ item }}.ldif.j2'
    dest: '/tmp/{{ item }}.ldif'
    owner: 'ldap'
    group: 'ldap'
    mode: '0644'
  loop: '{{ slapd_conf_ldif }}'

- name: Reload the OpenLDAP service.
  shell: echo ''
  notify: 'Ensure OpenLDAP service is enabled'
  when: slapd_yum_status is changed or slapd_db_config is changed or slapd_systemd is changed or slapd_conf_file is changed

- name: Force the handler to run immediately.
  meta: flush_handlers

- name: Waits for OpenLDAP service startup.
  wait_for:
    host: '{{ ansible_default_ipv4.address }}'
    port: '{{ slapd_port_arg.ldap }}'
    delay: '2'

- name: Enable the OpenLDAP TLS Configuration.
  command: 'ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/certs.ldif'
  register: slapd_conf_status
  failed_when:
    - "'already exists' not in slapd_conf_status.stdout"
    - "'modifying entry' not in slapd_conf_status.stdout"
    - "'adding new entry' not in slapd_conf_status.stdout"
  when: slapd_ssl | bool

- name: Enable the OpenLDAP syncprov module.
  command: 'ldapadd -Y EXTERNAL -H ldapi:// -f /tmp/syncprov_mod.ldif'
  when: slapd_servers | length > 1
  register: slapd_conf_status
  failed_when:
    - "'already exists' not in slapd_conf_status.stdout"
    - "'modifying entry' not in slapd_conf_status.stdout"
    - "'adding new entry' not in slapd_conf_status.stdout"

- name: Change the olcServerID on all servers.
  command: 'ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/olcserverid.ldif'
  register: slapd_conf_status
  failed_when:
    - "'already exists' not in slapd_conf_status.stdout"
    - "'modifying entry' not in slapd_conf_status.stdout"
    - "'adding new entry' not in slapd_conf_status.stdout"

- name: Change root password.
  command: 'ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/olcdatabase.ldif'
  register: slapd_conf_status
  failed_when:
    - "'already exists' not in slapd_conf_status.stdout"
    - "'modifying entry' not in slapd_conf_status.stdout"
    - "'adding new entry' not in slapd_conf_status.stdout"

- name: Server configuration.
  command: 'ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/configrep.ldif'
  register: slapd_conf_status
  failed_when:
    - "'already exists' not in slapd_conf_status.stdout"
    - "'modifying entry' not in slapd_conf_status.stdout"
    - "'adding new entry' not in slapd_conf_status.stdout"

- name: Enable Database operation.
  block:
    - name: Enable syncprov for hdb database.
      command: 'ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/syncprov.ldif'
      when: slapd_servers | length > 1
    - name: Add the OpenLDAP schemas.
      command: 'ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/{{ item }}.ldif'
      loop: '{{ slapd_conf_schema }}'
      register: slapd_conf_status
      failed_when:
        - "'already exists' not in slapd_conf_status.stdout"
        - "'modifying entry' not in slapd_conf_status.stdout"
        - "'adding new entry' not in slapd_conf_status.stdout"
    - name: FusionDirectory Schema setup.
      command: 'fusiondirectory-insert-schema -i /etc/openldap/schema/fusiondirectory/{{ item }}.schema'
      loop: '{{ slapd_fd_conf_schema }}'
      register: slapd_conf_status
      failed_when:
        - "'already exists' not in slapd_conf_status.stdout"
        - "'modifying entry' not in slapd_conf_status.stdout"
        - "'adding new entry' not in slapd_conf_status.stdout"
      when: slapd_fd_dept | bool
    - name: Configure hdb database.
      command: 'ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/olcdatabasehdb.ldif'
      register: slapd_conf_status
      failed_when:
        - "'already exists' not in slapd_conf_status.stdout"
        - "'modifying entry' not in slapd_conf_status.stdout"
        - "'adding new entry' not in slapd_conf_status.stdout"
    - name: Restrict the monitor permissions are given to only allowed monitoring users.
      command: 'ldapmodify -Y EXTERNAL  -H ldapi:/// -f /tmp/monitor.ldif'
    - name: Build the directory structure for your domain.
      command: 'ldapadd -x -w {{ slapd_root_pass }} -D "cn={{ slapd_root_user }},dc={{ datacenter }},dc={{ domain }}" -H ldapi:/// -f /tmp/base.ldif'
      register: slapd_conf_status
      failed_when:
        - "'already exists' not in slapd_conf_status.stdout"
        - "'modifying entry' not in slapd_conf_status.stdout"
        - "'adding new entry' not in slapd_conf_status.stdout"
  when: slapd_servers[0] in ansible_default_ipv4.address

- name: Remove the LDAP Data Interchange files.
  file:
    path: '/tmp/{{ item }}.ldif'
    state: 'absent'
  when: slapd_ldif_clean | bool
  changed_when: false
  failed_when: false
  loop: '{{ slapd_conf_ldif }}'
