---
- name: LDAP Data Interchange Files transfer.
  template:
    src: '{{ item }}.ldif.j2'
    dest: '/tmp/{{ item }}.ldif'
    owner: 'ldap'
    group: 'ldap'
    mode: '0644'
  loop: '{{ slapd_conf_ldif }}'
  no_log: true

- name: Enable syncprov for hdb database.
  command: 'ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/syncprov.ldif'

- name: Configure hdb database.
  command: 'ldapmodify -Y EXTERNAL  -H ldapi:/// -f /tmp/olcdatabasehdb.ldif'
  register: slapd_conf_status
  failed_when:
    - "'already exists' not in slapd_conf_status.stdout"
    - "'modifying entry' not in slapd_conf_status.stdout"
    - "'adding new entry' not in slapd_conf_status.stdout"

- name: Restrict the monitor access only to LDAP root.
  command: 'ldapmodify -Y EXTERNAL  -H ldapi:/// -f /tmp/monitor.ldif'

- name: Add the OpenLDAP schemas.
  command: 'ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/{{ item }}.ldif'
  loop: '{{ slapd_conf_schema }}'
  register: slapd_conf_status
  failed_when:
    - "'already exists' not in slapd_conf_status.stdout"
    - "'modifying entry' not in slapd_conf_status.stdout"
    - "'adding new entry' not in slapd_conf_status.stdout"

- name: Build the directory structure for your domain.
  command: 'ldapadd -x -w {{ slapd_root_pass | default("changeme") }} -D "cn={{ slapd_root_user }},dc={{ datacenter }},dc={{ domain }}" -H ldapi:// -f /tmp/base.ldif'
  register: slapd_conf_status
  failed_when:
    - "'already exists' not in slapd_conf_status.stdout"
    - "'modifying entry' not in slapd_conf_status.stdout"
    - "'adding new entry' not in slapd_conf_status.stdout"
