---
- name: Include tasks for specific OS.
  include: '{{ ansible_os_family }}.yml'

- name: Straight to getenforce selinux status.
  include: 'selinux.yml' 

- name: Include firewall tasks.
  include: 'firewall.yml'

- name: Include certificate tasks.
  include: 'certificates.yml'
  when: slapd_ssl | bool

- name: Hash OpenLDAP password.
  command: 'slappasswd -s {{ slapd_root_pass | default("changeme") }}'
  register: slapd_root_pass_out
  when: slapd_servers[0] in ansible_default_ipv4.address
  no_log: true

- name: Set the OpenLDAP password hash.
  set_fact:
    slapd_root_pass_hash: '{{ slapd_root_pass_out.stdout }}'
  when: slapd_root_pass_out.stdout is defined
  delegate_to: '{{ item }}'
  delegate_facts: true
  loop: '{{ groups[group_names[-1]] }}'

- name: Configuration the OpenLDAP.
  include: 'configureation.yml'

- name: Include replication tasks.
  include: 'replication.yml'
  when: slapd_servers | length > 1

- name: Include database tasks.
  include: 'database.yml'
  when: slapd_servers[0] in ansible_default_ipv4.address

- name: Include Fusiondirectory tasks.
  include: 'fusiondirectory.yml'
  when: slapd_fd_dept | bool