---
- name: Include tasks for specific OS.
  include: '{{ ansible_os_family }}.yml'

- name: Straight to getenforce selinux status.
  include: 'selinux.yml' 

- name: Include firewall tasks.
  include: 'firewall.yml'

- name: Configuration the OpenLDAP.
  include: 'configureation.yml'

- name: Include replication tasks.
  include: 'replication.yml'
  when: slapd_servers | length > 1

#- name: Include database tasks.
#  include: 'database.yml'
#  when: slapd_servers[0] in ansible_default_ipv4.address
