---
- name: Include OS-specific variables.
  include_vars: '{{ ansible_os_family }}.yml'

- name: Install the OpenLDAP packages.
  yum:
    name: '{{ slapd_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: slapd_yum_status
  until: slapd_yum_status is succeeded
  retries: 5
  delay: 2

- name: Fusiondirectory installation operation.
  block:
    - name: Add Fusiondirectory YUM repositories.
      yum_repository:
        name: '{{ slapd_fd_repo_name }}'
        description: '{{ slapd_fd_repo_name }} YUM repository'
        file: '{{ slapd_fd_repo_name }}'
        baseurl: '{{ slapd_fd_repo_url }}'
        gpgcheck: 'no'
        timeout: '60'
    - name: Add Fusiondirectory Extra YUM repositories.
      yum_repository:
        name: '{{ slapd_fd_extra_repo_name }}'
        description: '{{ slapd_fd_extra_repo_name }} YUM repository'
        file: '{{ slapd_fd_extra_repo_name }}'
        baseurl: '{{ slapd_fd_extra_repo_url }}'
        gpgcheck: 'no'
        timeout: '60'
    - name: Install the Fusiondirectory packages.
      yum:
        name: '{{ slapd_fd_packages }}'
        state: 'present'
        validate_certs: 'no'
        disable_gpg_check: 'yes'
      register: slapd_fd_yum_status
      until: slapd_fd_yum_status is succeeded
      retries: 5
      delay: 2
  when: slapd_fd_dept | bool

- name: Add EPEL YUM repositories.
  yum_repository:
    name: '{{ slapd_epel_repo_name }}'
    description: '{{ slapd_epel_repo_name }} YUM repo'
    file: '{{ slapd_epel_repo_name }}'
    baseurl: '{{ slapd_epel_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'
  when:
    - slapd_backupset_arg.cloud_rsync | bool
    - slapd_backupset_arg.cloud_drive is defined

- name: Install the Rclone command line program packages.
  yum:
    name: 'rclone'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
    update_cache: 'yes'
  register: slapd_rc_yum_status
  until: slapd_rc_yum_status is succeeded
  retries: 5
  delay: 2
  when:
    - slapd_backupset_arg.cloud_rsync | bool
    - slapd_backupset_arg.cloud_drive is defined
