---
- name: Include OS-specific variables.
  include_vars: '{{ ansible_os_family }}.yml'

- name: Install the OpenLDAP packages.
  yum:
    name: '{{ slapd_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: slapd_yum_status
  until: slapd_yum_status is succeeded
  retries: 5
  delay: 2
